version: '3'

services:
  jira:
    container_name: jira
    depends_on:
      - postgresql
    image: atlassian/jira-software:8.5.4
    networks:
      - jiranet
    volumes:
      - jiradata:/var/atlassian/jira
    ports:
      - '8080:8080'
    environment:
      - 'ATL_JDBC_URL=jdbc:postgresql://34.125.118.11:5432/jiradb'
      - 'ATL_JDBC_USER=jiradbuser'
      - 'ATL_JDBC_PASSWORD=admin123'
      - 'ATL_DB_DRIVER=org.postgresql.Driver'
      - 'ATL_DB_TYPE=postgres72'
      - 'ATL_DB_SCHEMA_NAME=public'
      - 'SETENV_JVM_MINIMUM_MEMORY=2048m'
      - 'SETENV_JVM_MAXIMUM_MEMORY=4096m'

  postgresql:
    container_name: postgres
    image: postgres:9.6
    ports:
      - '5432:5432'
    networks:
      - jiranet
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=jiradbuser'
      # CHANGE THE PASSWORD!
      - 'POSTGRES_PASSWORD=admin123'
      - 'POSTGRES_DB=jiradb'
      - 'POSTGRES_ENCODING=UNICODE'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'

volumes:
  jiradata:
    external: false
  postgresqldata:
    external: false

networks:
  jiranet:
    driver: bridge
